apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinel.web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "sentinel.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sentinel.web.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- include "sentinel.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: web
          image: {{ include "sentinel.image" (dict "registry" .Values.global.imageRegistry "repo" .Values.web.image.repository "tag" .Values.web.image.tag) }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "sentinel.secretName" . }}
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://{{ include "sentinel.fullname" . }}-api:{{ .Values.api.service.port }}/api/v1"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
      securityContext:
        fsGroup: 1000
