import { mkdirSync, writeFileSync, chmodSync } from 'fs';
import { join, dirname } from 'path';
import { PLAYWRIGHT_VERSION, SENTINEL_REPORTER_MARKER } from '@sentinel/shared';
import type { ShardManifest, Browser } from './types.js';

const BROWSER_DEVICE: Record<Browser, string> = {
  CHROMIUM: 'Desktop Chrome',
  FIREFOX: 'Desktop Firefox',
  WEBKIT: 'Desktop Safari',
};

// ── playwright.config.ts template ────────────────────────────────────────────

function buildPlaywrightConfig(manifest: ShardManifest): string {
  const projects = manifest.browsers
    .map(
      (b) =>
        `    { name: ${JSON.stringify(b.toLowerCase())}, use: { ...devices[${JSON.stringify(BROWSER_DEVICE[b])}] } }`,
    )
    .join(',\n');

  return `// Auto-generated by Sentinel runner — do not edit
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './specs',
  retries: 2,
  workers: ${manifest.workers ?? 1},
  reporter: [
    ['./reporters/sentinel-reporter.ts'],
    ['html', { outputFolder: 'report', open: 'never' }],
    ['json', { outputFile: 'results.json' }],
  ],
  use: {
    baseURL: ${JSON.stringify(manifest.environment.baseUrl)},
    trace: ${JSON.stringify(manifest.traceMode)},
    video: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },
  outputDir: './artifacts',
  projects: [
${projects}
  ],
});
`;
}

// ── fixtures/sentinel.ts template ────────────────────────────────────────────

function buildFixtures(manifest: ShardManifest): string {
  const vars = manifest.environment.vars;
  const secrets = manifest.environment.secrets;

  const varsEntries = Object.entries(vars)
    .map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n');

  const secretsEntries = Object.entries(secrets)
    .map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n');

  return `// Auto-generated by Sentinel runner — do not edit
import { test as base } from '@playwright/test';

export interface SentinelVars {
  [key: string]: string;
}

export interface SentinelSecrets {
  [key: string]: string;
}

export interface SentinelRun {
  runId: string;
  shortId: string;
  testEmail: string;
}

export const test = base.extend<{
  vars: SentinelVars;
  secrets: SentinelSecrets;
  run: SentinelRun;
}>({
  // eslint-disable-next-line no-empty-pattern
  vars: async ({}, use) => {
    await use({
${varsEntries}
    });
  },
  // eslint-disable-next-line no-empty-pattern
  secrets: async ({}, use) => {
    await use({
${secretsEntries}
    });
  },
  // eslint-disable-next-line no-empty-pattern
  run: async ({}, use) => {
    await use({
      runId: ${JSON.stringify(manifest.runId)},
      shortId: ${JSON.stringify(manifest.shortId)},
      testEmail: ${JSON.stringify(manifest.testEmail ?? '')},
    });
  },
});

export { expect } from '@playwright/test';
`;
}

// ── reporters/sentinel-reporter.ts template ───────────────────────────────────
// This file is executed INSIDE the Playwright test runner (Docker container or
// local process).  It must NOT import from runner source — it is self-contained.

function buildReporter(manifest: ShardManifest): string {
  return `// Auto-generated by Sentinel runner — do not edit
import type {
  FullConfig,
  FullResult,
  Reporter,
  Suite,
  TestCase,
  TestResult,
  TestStep,
} from '@playwright/test/reporter';

const MARKER = ${JSON.stringify(SENTINEL_REPORTER_MARKER)};
const RUN_ID = ${JSON.stringify(manifest.runId)};
const SHARD_INDEX = ${manifest.shardIndex};
const PW_VERSION = ${JSON.stringify(PLAYWRIGHT_VERSION)};

class SentinelReporter implements Reporter {
  private seq = 0;
  // Maps \`\${testId}:\${attemptIndex}\` → most-recently-active stepId
  private currentStepId = new Map<string, string>();

  private emit(type: string, payload: unknown): void {
    const event = {
      seq: this.seq++,
      ts: new Date().toISOString(),
      runId: RUN_ID,
      shardIndex: SHARD_INDEX,
      type,
      payload,
    };
    process.stdout.write(MARKER + ' ' + JSON.stringify(event) + '\\n');
  }

  onBegin(config: FullConfig, suite: Suite): void {
    this.emit('run.begin', {
      totalTests: suite.allTests().length,
      workers: config.workers,
      playwrightVersion: PW_VERSION,
    });
  }

  onTestBegin(test: TestCase, result: TestResult): void {
    this.emit('test.begin', {
      testId: test.id,
      title: test.title,
      filePath: test.location.file,
      projectLabel: test.parent.project()?.name ?? '',
      attemptIndex: result.retry,
    });
  }

  onStepBegin(test: TestCase, result: TestResult, step: TestStep): void {
    const stepId = \`\${test.id}:\${result.retry}:\${step.category}:\${step.startTime.getTime()}\`;
    const parentStepId = step.parent
      ? \`\${test.id}:\${result.retry}:\${step.parent.category}:\${step.parent.startTime.getTime()}\`
      : null;
    this.currentStepId.set(\`\${test.id}:\${result.retry}\`, stepId);
    this.emit('step.begin', {
      testId: test.id,
      attemptIndex: result.retry,
      stepId,
      parentStepId,
      title: step.title,
      category: step.category,
    });
  }

  onStepEnd(test: TestCase, result: TestResult, step: TestStep): void {
    const stepId = \`\${test.id}:\${result.retry}:\${step.category}:\${step.startTime.getTime()}\`;
    this.emit('step.end', {
      testId: test.id,
      attemptIndex: result.retry,
      stepId,
      status: step.error ? 'failed' : 'passed',
      durationMs: Math.round(step.duration),
      error: step.error?.message ?? null,
    });
  }

  onStdOut(
    chunk: string | Buffer,
    test: TestCase | undefined,
    result: TestResult | undefined,
  ): void {
    if (!test || !result) return;
    this.emit('test.stdout', {
      testId: test.id,
      attemptIndex: result.retry,
      chunk: chunk.toString(),
    });
  }

  onStdErr(
    chunk: string | Buffer,
    test: TestCase | undefined,
    result: TestResult | undefined,
  ): void {
    if (!test || !result) return;
    this.emit('test.stderr', {
      testId: test.id,
      attemptIndex: result.retry,
      chunk: chunk.toString(),
    });
  }

  onTestEnd(test: TestCase, result: TestResult): void {
    this.currentStepId.delete(\`\${test.id}:\${result.retry}\`);
    const firstError = result.errors[0];
    this.emit('test.end', {
      testId: test.id,
      attemptIndex: result.retry,
      status: result.status,
      durationMs: result.duration,
      error: firstError
        ? {
            name: 'Error',
            message: firstError.message ?? '',
            stack: firstError.stack,
            snippet: firstError.snippet,
          }
        : null,
      attachments: result.attachments.map((a) => ({
        name: a.name,
        contentType: a.contentType,
        path: a.path,
      })),
    });
  }

  onEnd(result: FullResult): void {
    this.emit('run.end', {
      status: result.status,
      durationMs: result.duration,
    });
  }
}

export default SentinelReporter;
`;
}

// ── Public API ────────────────────────────────────────────────────────────────

export async function materializeWorkspace(
  manifest: ShardManifest,
  workDir: string,
): Promise<void> {
  // Create directory layout
  mkdirSync(join(workDir, 'specs'), { recursive: true });
  mkdirSync(join(workDir, 'fixtures'), { recursive: true });
  mkdirSync(join(workDir, 'reporters'), { recursive: true });

  // package.json — pins @playwright/test to the sentinel-wide locked version
  writeFileSync(
    join(workDir, 'package.json'),
    JSON.stringify(
      {
        name: 'sentinel-workspace',
        private: true,
        type: 'module',
        dependencies: {
          '@playwright/test': PLAYWRIGHT_VERSION,
        },
      },
      null,
      2,
    ) + '\n',
  );

  // pnpm-lock.yaml placeholder (populated from prewarmed store in prod)
  writeFileSync(
    join(workDir, 'pnpm-lock.yaml'),
    `lockfileVersion: '9.0'\n`,
  );

  // playwright.config.ts
  writeFileSync(
    join(workDir, 'playwright.config.ts'),
    buildPlaywrightConfig(manifest),
  );

  // Test spec files
  for (const test of manifest.tests) {
    // Strip leading "specs/" prefix if present — we already write into specs/
    const relativePath = test.filePath.replace(/^specs\//, '');
    const destPath = join(workDir, 'specs', relativePath);
    // Ensure any nested sub-directories inside specs/ exist
    const dir = dirname(destPath);
    mkdirSync(dir, { recursive: true });
    writeFileSync(destPath, test.code);
  }

  // Playwright fixtures helper
  writeFileSync(
    join(workDir, 'fixtures', 'sentinel.ts'),
    buildFixtures(manifest),
  );

  // Custom NDJSON reporter
  writeFileSync(
    join(workDir, 'reporters', 'sentinel-reporter.ts'),
    buildReporter(manifest),
  );

  // Lock down the workspace directory
  try {
    chmodSync(workDir, 0o700);
  } catch {
    // Windows — chmod is a no-op; Docker containers run on Linux where it works
  }
}
